### START

### NUMPY PYTHON LIBRARY
- the practice set for this library contains 40 questions

In [1]:
import numpy as np

### 📌 SECTION A — Array Creation & Manipulation (Basics to Intermediate) 

1. Create a NumPy array from 1 to 100 (inclusive).

In [2]:
array1=np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Create a 5×5 matrix filled with random integers between 10 and 99. 

In [3]:
array=np.random.randint(10,99,[5,5])
array

array([[34, 69, 22, 79, 28],
       [40, 43, 33, 69, 40],
       [45, 18, 96, 16, 78],
       [15, 64, 37, 25, 14],
       [71, 49, 64, 10, 82]], dtype=int32)

3. Generate an array of 50 evenly spaced numbers between 0 and 5. 

In [4]:
array2=np.linspace(0,5,50)
array2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

4. Convert the list below into a NumPy float array: 
[10, 20, 30, 40, 50] 

In [5]:
lists=[10,20,30,40,50]
array3=np.array(lists,dtype=float)
array3

array([10., 20., 30., 40., 50.])

5. Create a 10-element array of zeroes and replace the 5th index with the 
value 99. 

In [6]:
array4=np.zeros(10,dtype=int)
array4[4]=99
array4

array([ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0])

6. Create an array of shape (3,4) with random floats and round the values to 2 
decimals. 

In [7]:
array5=np.random.randn(3,4)
array5

array([[-0.64933981,  1.13357223, -0.27466122, -0.12497461],
       [-1.98673706, -1.21251239,  0.04734932,  1.36707022],
       [-0.15799109,  0.68890811, -1.45814896,  0.49957406]])

7. Create a 4×4 identity matrix.

In [8]:
array6=np.eye(4,4,dtype=int)
array6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

8. Build a 3×3 matrix where every value is the row index + column index.

In [9]:
array7=np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)
array7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

9. Create a 4×3 array containing numbers from 1 to 12 reshaped using 
.reshape(). 

In [13]:
array8=np.arange(1,13,1)
reshaped=array8.reshape(4,3)
reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

10. Flatten a 2D array into a 1D array using ravel() and print shape 
before/after.

In [17]:
reshaped
flatten=reshaped.ravel()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 📌 SECTION B — Indexing, Slicing,Filtering 

11. Extract the 2nd, 3rd, and 4th elements from this array: 
a = np.array([5, 10, 15, 20, 25, 30]) 

In [19]:
a = np.array([5, 10, 15, 20, 25, 30]) 
print(a[1])
print(a[2])
print(a[3])

10
15
20


12. From the matrix below, extract the last two columns: 
m = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

In [25]:
m = np.array([[1,2,3], 
              [4,5,6],  # 3 rows and columns 
              [7,8,9]])
m[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

13. Filter only values > 50 from a random 1D array of 20 integers (0–100).

In [114]:
array9=np.random.randint(0,100,20)
arr=array9[array9>50]
arr

array([69, 64, 87, 58, 65, 86, 78, 64], dtype=int32)

14. From the array below, extract only even numbers:
a = np.array([2,5,7,9,12,14])

In [113]:
a = np.array([5, 10, 15, 20, 25, 30])
b=a[a%2==0]
print(b)
print(a)

[10 20 30]
[ 5 10 15 20 25 30]


15. Reverse the order of columns in a 2D array using slicing.

In [53]:
array10=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
reversearray=array10[:,::-1]
reversearray

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

16. Replace all negative values in the array with 0.

In [ ]:
array11=np.array([[1,-1,3],
                  [4,5,-6],
                  [-7,-8,9]])
array11[array11<0]=0
array11

array([[1, 0, 3],
       [4, 5, 0],
       [0, 0, 9]])

17. Check if the array contains any value equal to 25 (True/False).

In [67]:
array13=np.array([1,2,25,30,55,25,43,25])
array13.__contains__(25)

True

18. Extract every alternate row from a 6×3 matrix.

In [75]:
array14=np.random.randint(1,100,size=[6,3])
array14

array([[43, 87, 29],
       [59, 98, 84],
       [78, 48,  1],
       [68, 33, 60],
       [77, 13, 53],
       [41, 84, 23]], dtype=int32)

In [77]:
print(array14[0,:])
print(array14[2,:])
print(array14[4,:])

[43 87 29]
[78 48  1]
[77 13 53]


### 📌 SECTION C — Numeric Computation & Statistics

19. Compute the mean, median, std deviation, min, max for:
arr = np.array([10, 30, 40, 20, 50])

In [80]:
arr = np.array([10, 30, 40, 20, 50])
print(
    "mean: ",arr.mean(),
    "standard deviation: ",arr.std(),
    "minimum: ",arr.min(),
    "maximum:",arr.max(),
    "median: ",np.median(arr)
)

mean:  30.0 standard deviation:  14.142135623730951 minimum:  10 maximum: 50 median:  30.0


20. Normalize an array between 0 and 1 (min-max scaling).

In [84]:
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


21. Standardize an array (z-score normalization).

In [97]:
arr = np.array([10, 20, 30, 40, 50])
arr2=[]
mean=arr.mean()
std=arr.std()
zscorearray=(arr-mean/std)
print(zscorearray)

[ 7.87867966 17.87867966 27.87867966 37.87867966 47.87867966]


22. Calculate the percent change between consecutive elements in:
sales = np.array([100, 120, 150, 130, 180])

In [ ]:
sales = np.array([100, 120, 150, 130, 180])
percent_change = (sales[1:] - sales[:-1]) / sales[:-1] * 100
percent_change

array([ 20.        ,  25.        , -13.33333333,  38.46153846])

23. Apply the NumPy exponential, log, and sqrt functions on a 1D array.

In [116]:
array=np.array([10,20,30,40,50])
a=np.exp(array)
a

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [118]:
b=np.log(array)
b

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [119]:
c=np.sqrt(array)
c

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

24. Using vectorization, calculate squareroot of numbers from 1–15.

In [123]:
array=np.arange(1,16)
array
sqrt=np.sqrt(array)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

25. Calculate dot product of two 1D arrays of equal length.

In [127]:
array1=np.arange(1,6)
array2=np.arange(6,11)
array3=array1*array2
array3

array([ 6, 14, 24, 36, 50])

26. Calculate matrix multiplication (@) for two 3×3 matrices.

In [128]:
m1=np.random.randint(0,100,size=[3,3],dtype=int)
m1

array([[54, 68, 24],
       [47, 94, 39],
       [27, 72, 50]], dtype=int32)

In [129]:
m2=np.random.randint(0,100,size=[3,3],dtype=int)
m2

array([[60, 84, 72],
       [93, 97, 59],
       [25,  4, 18]], dtype=int32)

In [130]:
m3=m1*m2
m3

array([[3240, 5712, 1728],
       [4371, 9118, 2301],
       [ 675,  288,  900]], dtype=int32)

27. Compute the correlation matrix for:
data = np.array([[10,20,30],
[40,50,60],
[10,20,15]])

In [132]:
data = np.array([[10,20,30],
                [40,50,60],
                [10,20,15]])
m=np.corrcoef(data,rowvar=False)
m

array([[1.        , 1.        , 0.94491118],
       [1.        , 1.        , 0.94491118],
       [0.94491118, 0.94491118, 1.        ]])

28. Get unique values and their counts from an array containing duplicates.

In [ ]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
values,count=np.unique(arr,return_counts=True)
print(f"values: {values}")
print(f"count: {count}")

values: [1 2 3 4 5]
count: [1 2 1 3 1]


### 📌 SECTION D — Reshaping, Joining, Splitting

29. Reshape a 1D array of 24 values into (4,6), then reshape into (6,4).

In [144]:
array=np.random.randint(1,100,24)
array

array([31,  3, 26, 15,  9, 56, 98, 10, 65, 70, 13, 96,  2, 24,  5, 75, 34,
       66,  6, 47, 59, 42, 79, 37], dtype=int32)

In [145]:
reshaped1=array.reshape(4,6)
reshaped1

array([[31,  3, 26, 15,  9, 56],
       [98, 10, 65, 70, 13, 96],
       [ 2, 24,  5, 75, 34, 66],
       [ 6, 47, 59, 42, 79, 37]], dtype=int32)

In [146]:
reshaped2=array.reshape(6,4)
reshaped2

array([[31,  3, 26, 15],
       [ 9, 56, 98, 10],
       [65, 70, 13, 96],
       [ 2, 24,  5, 75],
       [34, 66,  6, 47],
       [59, 42, 79, 37]], dtype=int32)

30. Stack two arrays vertically:
x = [1,2,3]
y = [4,5,6]

In [153]:
x = [1,2,3]
y = [4,5,6]
vstack=np.vstack([x,y])
vstack

array([[1, 2, 3],
       [4, 5, 6]])

31. Stack the same arrays horizontally.

In [154]:
hstack=np.hstack((x,y))
hstack

array([1, 2, 3, 4, 5, 6])

32. Split an array of 12 numbers into 3 equal parts.

In [155]:
array=np.random.randint(0,100,12)
array

array([67, 37,  0, 37, 98, 89,  6, 67, 93, 73, 31, 23], dtype=int32)

In [156]:
np.split(array,3)

[array([67, 37,  0, 37], dtype=int32),
 array([98, 89,  6, 67], dtype=int32),
 array([93, 73, 31, 23], dtype=int32)]

33. Concatenate three separate 1D arrays into one final array.

In [159]:
a1,a2,a3=np.arange(0,6),np.arange(6,11),np.arange(11,16)

In [168]:
a=np.concat((a1,a2,a3))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

34. Repeat each element of an array 3 times using NumPy.

In [177]:
a=np.arange(0,5,dtype=int)
a

array([0, 1, 2, 3, 4])

In [178]:
rep=a.repeat(3)
rep

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

getting random float numbers

In [176]:
b=np.random.uniform(low=1.0,high=10.0,size=10)
b

array([6.74439256, 7.54834517, 3.54964794, 3.50684072, 2.17939659,
       7.49475887, 8.7150795 , 3.43130035, 6.26789189, 5.92528007])

### 📌 SECTION E — Broadcasting, Vectorization & Random

35. Add a 1D array to a 2D array using broadcasting (3×3 + 1×3).

In [179]:
a1=np.random.randint(0,100,size=[3,3])
a1

array([[41, 26, 25],
       [31, 75, 88],
       [54, 77, 20]], dtype=int32)

In [190]:
a2=np.random.randint(1,100,[1,3])
a2

array([[25, 32, 91]], dtype=int32)

In [191]:
a=a1+a2
a

array([[ 66,  58, 116],
       [ 56, 107, 179],
       [ 79, 109, 111]], dtype=int32)

36. Multiply a column vector (3×1) with a row vector (1×4) → output must be 3×4.

In [193]:
row_vect=np.random.randint(1,100,[1,4])
col_vec=a2=np.random.randint(1,100,[3,1])
print(row_vect)
print(col_vec)

[[51 95 90 88]]
[[63]
 [ 3]
 [77]]


In [194]:
m=col_vec*row_vect
m

array([[3213, 5985, 5670, 5544],
       [ 153,  285,  270,  264],
       [3927, 7315, 6930, 6776]], dtype=int32)

37. Use broadcasting to subtract the column mean from each column of a 5×5 matrix.

In [195]:
array=np.random.randint(1,100,size=[5,5])
array

array([[ 2, 16, 64, 19, 35],
       [20, 95, 55, 22, 11],
       [80, 61, 86, 69, 43],
       [43, 97, 19, 59, 82],
       [75, 17, 25, 15,  1]], dtype=int32)

the columns and rows of the matrix can be split in rows and columns using vsplit and Hsplit

In [201]:
col=np.hsplit(array,5)
col

[array([[ 2],
        [20],
        [80],
        [43],
        [75]], dtype=int32),
 array([[16],
        [95],
        [61],
        [97],
        [17]], dtype=int32),
 array([[64],
        [55],
        [86],
        [19],
        [25]], dtype=int32),
 array([[19],
        [22],
        [69],
        [59],
        [15]], dtype=int32),
 array([[35],
        [11],
        [43],
        [82],
        [ 1]], dtype=int32)]

In [202]:
np.vsplit(array,5)

[array([[ 2, 16, 64, 19, 35]], dtype=int32),
 array([[20, 95, 55, 22, 11]], dtype=int32),
 array([[80, 61, 86, 69, 43]], dtype=int32),
 array([[43, 97, 19, 59, 82]], dtype=int32),
 array([[75, 17, 25, 15,  1]], dtype=int32)]

In [206]:
col[4]

array([[35],
       [11],
       [43],
       [82],
       [ 1]], dtype=int32)

in numpy azis=0 means column wise and axis 1 is row wise 

In [217]:
colmean=np.mean(array,axis=0)
r=array-colmean
r

array([[-42. , -41.2,  14.2, -17.8,   0.6],
       [-24. ,  37.8,   5.2, -14.8, -23.4],
       [ 36. ,   3.8,  36.2,  32.2,   8.6],
       [ -1. ,  39.8, -30.8,  22.2,  47.6],
       [ 31. , -40.2, -24.8, -21.8, -33.4]])

38. Generate a 4×4 matrix of random floats (0–1) with seed=42.

In [ ]:
array=np.random.