### START

### NUMPY PYTHON LIBRARY
- the practice set for this library contains 40 questions

In [1]:
import numpy as np

### 📌 SECTION A — Array Creation & Manipulation (Basics to Intermediate) 

1. Create a NumPy array from 1 to 100 (inclusive).

In [2]:
array1=np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Create a 5×5 matrix filled with random integers between 10 and 99. 

In [3]:
array=np.random.randint(10,99,[5,5])
array

array([[34, 69, 22, 79, 28],
       [40, 43, 33, 69, 40],
       [45, 18, 96, 16, 78],
       [15, 64, 37, 25, 14],
       [71, 49, 64, 10, 82]], dtype=int32)

3. Generate an array of 50 evenly spaced numbers between 0 and 5. 

In [4]:
array2=np.linspace(0,5,50)
array2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

4. Convert the list below into a NumPy float array: 
[10, 20, 30, 40, 50] 

In [5]:
lists=[10,20,30,40,50]
array3=np.array(lists,dtype=float)
array3

array([10., 20., 30., 40., 50.])

5. Create a 10-element array of zeroes and replace the 5th index with the 
value 99. 

In [6]:
array4=np.zeros(10,dtype=int)
array4[4]=99
array4

array([ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0])

6. Create an array of shape (3,4) with random floats and round the values to 2 
decimals. 

In [7]:
array5=np.random.randn(3,4)
array5

array([[-0.64933981,  1.13357223, -0.27466122, -0.12497461],
       [-1.98673706, -1.21251239,  0.04734932,  1.36707022],
       [-0.15799109,  0.68890811, -1.45814896,  0.49957406]])

7. Create a 4×4 identity matrix.

In [8]:
array6=np.eye(4,4,dtype=int)
array6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

8. Build a 3×3 matrix where every value is the row index + column index.

In [9]:
array7=np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)
array7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

9. Create a 4×3 array containing numbers from 1 to 12 reshaped using 
.reshape(). 

In [13]:
array8=np.arange(1,13,1)
reshaped=array8.reshape(4,3)
reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

10. Flatten a 2D array into a 1D array using ravel() and print shape 
before/after.

In [17]:
reshaped
flatten=reshaped.ravel()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 📌 SECTION B — Indexing, Slicing,Filtering 

11. Extract the 2nd, 3rd, and 4th elements from this array: 
a = np.array([5, 10, 15, 20, 25, 30]) 

In [19]:
a = np.array([5, 10, 15, 20, 25, 30]) 
print(a[1])
print(a[2])
print(a[3])

10
15
20


12. From the matrix below, extract the last two columns: 
m = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

In [25]:
m = np.array([[1,2,3], 
              [4,5,6],  # 3 rows and columns 
              [7,8,9]])
m[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

13. Filter only values > 50 from a random 1D array of 20 integers (0–100).

In [30]:
array9=np.random.randint(0,100,20)
array9
for i in array9:
    if i>50:
        print(i)
    else:
        continue

94
59
87
79
91
58
84
76
67


14. From the array below, extract only even numbers:
a = np.array([2,5,7,9,12,14])

In [31]:
a = np.array([5, 10, 15, 20, 25, 30])
for i in a:
    if i%2==0:
        print(f"{i} is an even number!!!")
    else:
        continue

10 is an even number!!!
20 is an even number!!!
30 is an even number!!!


15. Reverse the order of columns in a 2D array using slicing.

In [53]:
array10=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
reversearray=array10[:,::-1]
reversearray

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

16. Replace all negative values in the array with 0.

In [66]:
array11=np.array([[1,-1,3],
                  [4,5,-6],
                  [-7,-8,9]])
array12=[]
for i in range(0,3,1):
    for j in range(0,3,1):
       if array11[i,j]<0:
           array11[i,j]=0
       else:
           continue
array11


array([[1, 0, 3],
       [4, 5, 0],
       [0, 0, 9]])

17. Check if the array contains any value equal to 25 (True/False).

In [67]:
array13=np.array([1,2,25,30,55,25,43,25])
array13.__contains__(25)

True

18. Extract every alternate row from a 6×3 matrix.

In [75]:
array14=np.random.randint(1,100,size=[6,3])
array14

array([[43, 87, 29],
       [59, 98, 84],
       [78, 48,  1],
       [68, 33, 60],
       [77, 13, 53],
       [41, 84, 23]], dtype=int32)

In [77]:
print(array14[0,:])
print(array14[2,:])
print(array14[4,:])

[43 87 29]
[78 48  1]
[77 13 53]


### 📌 SECTION C — Numeric Computation & Statistics