### START

### NUMPY PYTHON LIBRARY
- the practice set for this library contains 40 questions

In [12]:
import numpy as np

### 📌 SECTION A — Array Creation & Manipulation (Basics to Intermediate) 

1. Create a NumPy array from 1 to 100 (inclusive).

In [13]:
array1=np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Create a 5×5 matrix filled with random integers between 10 and 99. 

In [14]:
array=np.random.randint(10,99,[5,5])
array

array([[83, 84, 24, 93, 27],
       [26, 58, 20, 88, 95],
       [51, 69, 42, 83, 85],
       [29, 82, 48, 93, 24],
       [42, 89, 97, 76, 68]], dtype=int32)

3. Generate an array of 50 evenly spaced numbers between 0 and 5. 

In [15]:
array2=np.linspace(0,5,50)
array2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

4. Convert the list below into a NumPy float array: 
[10, 20, 30, 40, 50] 

In [16]:
lists=[10,20,30,40,50]
array3=np.array(lists,dtype=float)
array3

array([10., 20., 30., 40., 50.])

5. Create a 10-element array of zeroes and replace the 5th index with the 
value 99. 

In [17]:
array4=np.zeros(10,dtype=int)
array4[4]=99
array4

array([ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0])

6. Create an array of shape (3,4) with random floats and round the values to 2 
decimals. 

In [18]:
array5=np.random.randn(3,4)
array5
rounded=np.round(array5)
rounded

array([[ 0., -2., -1.,  0.],
       [-0.,  1., -0.,  0.],
       [-2.,  1., -0.,  1.]])

7. Create a 4×4 identity matrix.

In [19]:
array6=np.eye(4,4,dtype=int)
array6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

8. Build a 3×3 matrix where every value is the row index + column index.

In [20]:
array7=np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)
array7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

9. Create a 4×3 array containing numbers from 1 to 12 reshaped using 
.reshape(). 

In [21]:
array8=np.arange(1,13,1)
reshaped=array8.reshape(4,3)
reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

10. Flatten a 2D array into a 1D array using ravel() and print shape 
before/after.

In [22]:
reshaped
flatten=reshaped.ravel()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 📌 SECTION B — Indexing, Slicing,Filtering 

11. Extract the 2nd, 3rd, and 4th elements from this array: 
a = np.array([5, 10, 15, 20, 25, 30]) 

In [23]:
a = np.array([5, 10, 15, 20, 25, 30]) 
print(a[1])
print(a[2])
print(a[3])

10
15
20


12. From the matrix below, extract the last two columns: 
m = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

In [24]:
m = np.array([[1,2,3], 
              [4,5,6],  # 3 rows and columns 
              [7,8,9]])
m[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

13. Filter only values > 50 from a random 1D array of 20 integers (0–100).

In [25]:
array9=np.random.randint(0,100,20)
arr=array9[array9>50]
arr

array([93, 77, 85, 85, 53, 83], dtype=int32)

14. From the array below, extract only even numbers:
a = np.array([2,5,7,9,12,14])

In [26]:
a = np.array([5, 10, 15, 20, 25, 30])
a=a[a%2==0]
print(a)

[10 20 30]


15. Reverse the order of columns in a 2D array using slicing.

In [27]:
array10=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
reversearray=array10[:,::-1]
reversearray

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

16. Replace all negative values in the array with 0.

In [28]:
array11=np.array([[1,-1,3],
                  [4,5,-6],
                  [-7,-8,9]])
array11[array11<0]=0
array11

array([[1, 0, 3],
       [4, 5, 0],
       [0, 0, 9]])

17. Check if the array contains any value equal to 25 (True/False).

In [29]:
array13=np.array([1,2,25,30,55,25,43,25])
array13.__contains__(25)

True

18. Extract every alternate row from a 6×3 matrix.

In [30]:
array14=np.random.randint(1,100,size=[6,3])
array14

array([[73, 73, 68],
       [70, 16, 11],
       [96, 25, 91],
       [66, 29,  1],
       [35, 72, 27],
       [84, 20, 26]], dtype=int32)

In [31]:
print(array14[0,:])
print(array14[2,:])
print(array14[4,:])

[73 73 68]
[96 25 91]
[35 72 27]


### 📌 SECTION C — Numeric Computation & Statistics

19. Compute the mean, median, std deviation, min, max for:
arr = np.array([10, 30, 40, 20, 50])

In [32]:
arr = np.array([10, 30, 40, 20, 50])
print(
    "mean: ",arr.mean(),
    "standard deviation: ",arr.std(),
    "minimum: ",arr.min(),
    "maximum:",arr.max(),
    "median: ",np.median(arr)
)

mean:  30.0 standard deviation:  14.142135623730951 minimum:  10 maximum: 50 median:  30.0


20. Normalize an array between 0 and 1 (min-max scaling).

In [33]:
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


21. Standardize an array (z-score normalization).

In [34]:
arr = np.array([10, 20, 30, 40, 50])
arr2=[]
mean=arr.mean()
std=arr.std()
zscorearray=((arr-mean)/std)
print(zscorearray)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


22. Calculate the percent change between consecutive elements in:
sales = np.array([100, 120, 150, 130, 180])

In [35]:
sales = np.array([100, 120, 150, 130, 180])
percent_change = (sales[1:] - sales[:-1]) / sales[:-1] * 100
percent_change

array([ 20.        ,  25.        , -13.33333333,  38.46153846])

23. Apply the NumPy exponential, log, and sqrt functions on a 1D array.

In [36]:
array=np.array([10,20,30,40,50])
a=np.exp(array)
a

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [37]:
b=np.log(array)
b

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [38]:
c=np.sqrt(array)
c

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

24. Using vectorization, calculate squareroot of numbers from 1–15.

In [39]:
array=np.arange(1,16)
array
sqrt=np.sqrt(array)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

25. Calculate dot product of two 1D arrays of equal length.

In [1]:
import numpy as np
array1=np.arange(1,6)
array2=np.arange(6,11)
array3=np.dot(array1,array2)
array3

np.int64(130)

26. Calculate matrix multiplication (@) for two 3×3 matrices.

In [4]:
m1=np.random.randint(0,100,size=[3,3],dtype=int)
m1

array([[ 6,  3, 80],
       [70, 15, 38],
       [58,  4, 59]], dtype=int32)

In [5]:
m2=np.random.randint(0,100,size=[3,3],dtype=int)
m2

array([[71, 67, 30],
       [55, 70, 25],
       [39, 37, 65]], dtype=int32)

In [6]:
m3=m1 @ m2
m3

array([[3711, 3572, 5455],
       [7277, 7146, 4945],
       [6639, 6349, 5675]], dtype=int32)

27. Compute the correlation matrix for:
data = np.array([[10,20,30],
[40,50,60],
[10,20,15]])

In [40]:
data = np.array([[10,20,30],
                [40,50,60],
                [10,20,15]])
m=np.corrcoef(data,rowvar=False)
m

array([[1.        , 1.        , 0.94491118],
       [1.        , 1.        , 0.94491118],
       [0.94491118, 0.94491118, 1.        ]])

28. Get unique values and their counts from an array containing duplicates.

In [41]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
values,count=np.unique(arr,return_counts=True)
print(f"values: {values}")
print(f"count: {count}")

values: [1 2 3 4 5]
count: [1 2 1 3 1]


### 📌 SECTION D — Reshaping, Joining, Splitting

29. Reshape a 1D array of 24 values into (4,6), then reshape into (6,4).

In [42]:
array=np.random.randint(1,100,24)
array

array([94, 74, 18, 91, 77, 47, 30, 50,  2, 21, 52, 16, 71, 58, 67, 41, 15,
       25, 69, 84, 62, 83, 30, 66], dtype=int32)

In [43]:
reshaped1=array.reshape(4,6)
reshaped1

array([[94, 74, 18, 91, 77, 47],
       [30, 50,  2, 21, 52, 16],
       [71, 58, 67, 41, 15, 25],
       [69, 84, 62, 83, 30, 66]], dtype=int32)

In [44]:
reshaped2=array.reshape(6,4)
reshaped2

array([[94, 74, 18, 91],
       [77, 47, 30, 50],
       [ 2, 21, 52, 16],
       [71, 58, 67, 41],
       [15, 25, 69, 84],
       [62, 83, 30, 66]], dtype=int32)

30. Stack two arrays vertically:
x = [1,2,3]
y = [4,5,6]

In [45]:
x = [1,2,3]
y = [4,5,6]
vstack=np.vstack([x,y])
vstack

array([[1, 2, 3],
       [4, 5, 6]])

31. Stack the same arrays horizontally.

In [46]:
hstack=np.hstack((x,y))
hstack

array([1, 2, 3, 4, 5, 6])

32. Split an array of 12 numbers into 3 equal parts.

In [10]:
array=np.random.randint(0,100,12)
array

array([73, 51,  1, 87, 26, 91, 33, 75, 86, 24, 25, 21], dtype=int32)

In [11]:
np.split(array,3)

[array([73, 51,  1, 87], dtype=int32),
 array([26, 91, 33, 75], dtype=int32),
 array([86, 24, 25, 21], dtype=int32)]

33. Concatenate three separate 1D arrays into one final array.

In [7]:
a1,a2,a3=np.arange(0,6),np.arange(6,11),np.arange(11,16)

In [8]:
a=np.concatenate((a1,a2,a3))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

34. Repeat each element of an array 3 times using NumPy.

In [47]:
a=np.arange(0,5,dtype=int)
a

array([0, 1, 2, 3, 4])

In [48]:
rep=a.repeat(3)
rep

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

getting random float numbers

In [49]:
b=np.random.uniform(low=1.0,high=10.0,size=10)
b

array([5.1471703 , 3.29860944, 3.48742617, 6.54158062, 7.85608632,
       8.98529399, 1.77297812, 8.68477127, 3.06778057, 1.81010964])

### 📌 SECTION E — Broadcasting, Vectorization & Random

35. Add a 1D array to a 2D array using broadcasting (3×3 + 1×3).

In [50]:
a1=np.random.randint(0,100,size=[3,3])
a1

array([[36, 89, 70],
       [64, 51, 31],
       [86,  4, 32]], dtype=int32)

In [51]:
a2=np.random.randint(1,100,[1,3])
a2

array([[38, 99, 38]], dtype=int32)

In [52]:
a=a1+a2
a

array([[ 74, 188, 108],
       [102, 150,  69],
       [124, 103,  70]], dtype=int32)

36. Multiply a column vector (3×1) with a row vector (1×4) → output must be 3×4.

In [53]:
row_vect=np.random.randint(1,100,[1,4])
col_vec=a2=np.random.randint(1,100,[3,1])
print(row_vect)
print(col_vec)

[[54 65 76 14]]
[[39]
 [56]
 [41]]


In [54]:
m=col_vec*row_vect
m

array([[2106, 2535, 2964,  546],
       [3024, 3640, 4256,  784],
       [2214, 2665, 3116,  574]], dtype=int32)

37. Use broadcasting to subtract the column mean from each column of a 5×5 matrix.

In [55]:
array=np.random.randint(1,100,size=[5,5])
array

array([[77, 80, 12, 93, 48],
       [24, 87, 42, 97, 51],
       [80, 42, 51, 53, 88],
       [66, 94, 50, 12, 36],
       [16, 27,  5, 11, 31]], dtype=int32)

the columns and rows of the matrix can be split in rows and columns using vsplit and Hsplit

In [56]:
col=np.hsplit(array,5)
col

[array([[77],
        [24],
        [80],
        [66],
        [16]], dtype=int32),
 array([[80],
        [87],
        [42],
        [94],
        [27]], dtype=int32),
 array([[12],
        [42],
        [51],
        [50],
        [ 5]], dtype=int32),
 array([[93],
        [97],
        [53],
        [12],
        [11]], dtype=int32),
 array([[48],
        [51],
        [88],
        [36],
        [31]], dtype=int32)]

In [57]:
np.vsplit(array,5)

[array([[77, 80, 12, 93, 48]], dtype=int32),
 array([[24, 87, 42, 97, 51]], dtype=int32),
 array([[80, 42, 51, 53, 88]], dtype=int32),
 array([[66, 94, 50, 12, 36]], dtype=int32),
 array([[16, 27,  5, 11, 31]], dtype=int32)]

In [58]:
col[4]

array([[48],
       [51],
       [88],
       [36],
       [31]], dtype=int32)

in numpy azis=0 means column wise and axis 1 is row wise 

In [59]:
colmean=np.mean(array,axis=0)
r=array-colmean
r

array([[ 24.4,  14. , -20. ,  39.8,  -2.8],
       [-28.6,  21. ,  10. ,  43.8,   0.2],
       [ 27.4, -24. ,  19. ,  -0.2,  37.2],
       [ 13.4,  28. ,  18. , -41.2, -14.8],
       [-36.6, -39. , -27. , -42.2, -19.8]])

38. Generate a 4×4 matrix of random floats (0–1) with seed=42.

In [60]:
np.random.seed(42)
array=np.random.rand(4,4)
array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

39. Shuffle an array randomly using NumPy only (no Python shuffle).

In [61]:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)

[3 1 5 2 4]


40. Real Analyst Scenario:
You have 24 months of monthly sales:
sales = np.arange(1,25)
Reshape it into 12 rows × 2 columns (12 months × 2 years) for comparison.

In [62]:
sales=np.random.randint(1000,20000,24)
sales

array([ 9666, 19942, 19431,  3747,  1189,  4005,  2899,  2267, 18912,
       12394,  4556,  4890,  9838, 15502, 11627,  9792, 11555, 11253,
        9433, 11233, 12016,  3612, 16787, 18159], dtype=int32)

In [63]:
year_sale=sales.reshape(12,2)
year_sale

array([[ 9666, 19942],
       [19431,  3747],
       [ 1189,  4005],
       [ 2899,  2267],
       [18912, 12394],
       [ 4556,  4890],
       [ 9838, 15502],
       [11627,  9792],
       [11555, 11253],
       [ 9433, 11233],
       [12016,  3612],
       [16787, 18159]], dtype=int32)

### END