### START

### NUMPY PYTHON LIBRARY
- the practice set for this library contains 40 questions

In [85]:
import numpy as np

### 📌 SECTION A — Array Creation & Manipulation (Basics to Intermediate) 

1. Create a NumPy array from 1 to 100 (inclusive).

In [84]:
array1=np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Create a 5×5 matrix filled with random integers between 10 and 99. 

In [83]:
array=np.random.randint(10,99,[5,5])
array

array([[68, 45, 28, 76, 28],
       [29, 80, 61, 42, 49],
       [48, 91, 10, 20, 66],
       [98, 59, 32, 40, 51],
       [16, 25, 69, 11, 10]], dtype=int32)

3. Generate an array of 50 evenly spaced numbers between 0 and 5. 

In [82]:
array2=np.linspace(0,5,50)
array2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

4. Convert the list below into a NumPy float array: 
[10, 20, 30, 40, 50] 

In [81]:
lists=[10,20,30,40,50]
array3=np.array(lists,dtype=float)
array3

array([10., 20., 30., 40., 50.])

5. Create a 10-element array of zeroes and replace the 5th index with the 
value 99. 

In [80]:
array4=np.zeros(10,dtype=int)
array4[4]=99
array4

array([ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0])

6. Create an array of shape (3,4) with random floats and round the values to 2 
decimals. 

In [79]:
array5=np.random.randn(3,4)
array5

array([[-1.32187695, -0.6682467 , -0.137291  ,  1.40132156],
       [-0.04540266,  0.21693673,  0.51242373,  0.54348869],
       [ 0.02809946, -1.19708706,  0.7896728 ,  0.43148946]])

7. Create a 4×4 identity matrix.

In [78]:
array6=np.eye(4,4,dtype=int)
array6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

8. Build a 3×3 matrix where every value is the row index + column index.

In [77]:
array7=np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)
array7

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

9. Create a 4×3 array containing numbers from 1 to 12 reshaped using 
.reshape(). 

In [75]:
array8=np.arange(1,13,1)
reshaped=array8.reshape(4,3)
reshaped

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

10. Flatten a 2D array into a 1D array using ravel() and print shape 
before/after.

In [76]:
reshaped
flatten=reshaped.ravel()
flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 📌 SECTION B — Indexing, Slicing,Filtering 

11. Extract the 2nd, 3rd, and 4th elements from this array: 
a = np.array([5, 10, 15, 20, 25, 30]) 

In [73]:
a = np.array([5, 10, 15, 20, 25, 30]) 
print(a[1])
print(a[2])
print(a[3])

10
15
20


12. From the matrix below, extract the last two columns: 
m = np.array([[1,2,3], 
              [4,5,6], 
              [7,8,9]])

In [72]:
m = np.array([[1,2,3], 
              [4,5,6],  # 3 rows and columns 
              [7,8,9]])
m[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

13. Filter only values > 50 from a random 1D array of 20 integers (0–100).

In [70]:
array9=np.random.randint(0,100,20)
arr=array9[array9>50]
arr

array([58, 91, 53, 86, 95, 96, 52, 89, 69, 67, 54, 74], dtype=int32)

14. From the array below, extract only even numbers:
a = np.array([2,5,7,9,12,14])

In [71]:
a = np.array([5, 10, 15, 20, 25, 30])
b=a[a%2==0]
print(b)
print(a)

[10 20 30]
[ 5 10 15 20 25 30]


15. Reverse the order of columns in a 2D array using slicing.

In [68]:
array10=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
reversearray=array10[:,::-1]
reversearray

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

16. Replace all negative values in the array with 0.

In [67]:
array11=np.array([[1,-1,3],
                  [4,5,-6],
                  [-7,-8,9]])
array11[array11<0]=0
array11

array([[1, 0, 3],
       [4, 5, 0],
       [0, 0, 9]])

17. Check if the array contains any value equal to 25 (True/False).

In [66]:
array13=np.array([1,2,25,30,55,25,43,25])
array13.__contains__(25)

True

18. Extract every alternate row from a 6×3 matrix.

In [64]:
array14=np.random.randint(1,100,size=[6,3])
array14

array([[51, 44, 24],
       [79, 59, 32],
       [96, 88, 52],
       [62, 58, 52],
       [12, 39,  2],
       [ 3, 56, 81]], dtype=int32)

In [65]:
print(array14[0,:])
print(array14[2,:])
print(array14[4,:])

[51 44 24]
[96 88 52]
[12 39  2]


### 📌 SECTION C — Numeric Computation & Statistics

19. Compute the mean, median, std deviation, min, max for:
arr = np.array([10, 30, 40, 20, 50])

In [63]:
arr = np.array([10, 30, 40, 20, 50])
print(
    "mean: ",arr.mean(),
    "standard deviation: ",arr.std(),
    "minimum: ",arr.min(),
    "maximum:",arr.max(),
    "median: ",np.median(arr)
)

mean:  30.0 standard deviation:  14.142135623730951 minimum:  10 maximum: 50 median:  30.0


20. Normalize an array between 0 and 1 (min-max scaling).

In [62]:
arr = np.array([10, 20, 30, 40, 50])
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


21. Standardize an array (z-score normalization).

In [60]:
arr = np.array([10, 20, 30, 40, 50])
arr2=[]
mean=arr.mean()
std=arr.std()
zscorearray=(arr-mean/std)
print(zscorearray)

[ 7.87867966 17.87867966 27.87867966 37.87867966 47.87867966]


22. Calculate the percent change between consecutive elements in:
sales = np.array([100, 120, 150, 130, 180])

In [61]:
sales = np.array([100, 120, 150, 130, 180])
percent_change = (sales[1:] - sales[:-1]) / sales[:-1] * 100
percent_change

array([ 20.        ,  25.        , -13.33333333,  38.46153846])

23. Apply the NumPy exponential, log, and sqrt functions on a 1D array.

In [57]:
array=np.array([10,20,30,40,50])
a=np.exp(array)
a

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [58]:
b=np.log(array)
b

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [55]:
c=np.sqrt(array)
c

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

24. Using vectorization, calculate squareroot of numbers from 1–15.

In [54]:
array=np.arange(1,16)
array
sqrt=np.sqrt(array)
sqrt

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335])

25. Calculate dot product of two 1D arrays of equal length.

In [53]:
array1=np.arange(1,6)
array2=np.arange(6,11)
array3=array1*array2
array3

array([ 6, 14, 24, 36, 50])

26. Calculate matrix multiplication (@) for two 3×3 matrices.

In [50]:
m1=np.random.randint(0,100,size=[3,3],dtype=int)
m1

array([[61, 74, 91],
       [88, 61, 96],
       [ 0, 26, 61]], dtype=int32)

In [51]:
m2=np.random.randint(0,100,size=[3,3],dtype=int)
m2

array([[76,  2, 69],
       [71, 26,  8],
       [61, 36, 96]], dtype=int32)

In [52]:
m3=m1*m2
m3

array([[4636,  148, 6279],
       [6248, 1586,  768],
       [   0,  936, 5856]], dtype=int32)

27. Compute the correlation matrix for:
data = np.array([[10,20,30],
[40,50,60],
[10,20,15]])

In [49]:
data = np.array([[10,20,30],
                [40,50,60],
                [10,20,15]])
m=np.corrcoef(data,rowvar=False)
m

array([[1.        , 1.        , 0.94491118],
       [1.        , 1.        , 0.94491118],
       [0.94491118, 0.94491118, 1.        ]])

28. Get unique values and their counts from an array containing duplicates.

In [48]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
values,count=np.unique(arr,return_counts=True)
print(f"values: {values}")
print(f"count: {count}")

values: [1 2 3 4 5]
count: [1 2 1 3 1]


### 📌 SECTION D — Reshaping, Joining, Splitting

29. Reshape a 1D array of 24 values into (4,6), then reshape into (6,4).

In [45]:
array=np.random.randint(1,100,24)
array

array([ 4, 94, 23, 15, 43, 29, 36, 13, 32, 71, 59, 86, 28, 66, 42, 45, 62,
       57,  6, 28, 28, 44, 84, 30], dtype=int32)

In [46]:
reshaped1=array.reshape(4,6)
reshaped1

array([[ 4, 94, 23, 15, 43, 29],
       [36, 13, 32, 71, 59, 86],
       [28, 66, 42, 45, 62, 57],
       [ 6, 28, 28, 44, 84, 30]], dtype=int32)

In [47]:
reshaped2=array.reshape(6,4)
reshaped2

array([[ 4, 94, 23, 15],
       [43, 29, 36, 13],
       [32, 71, 59, 86],
       [28, 66, 42, 45],
       [62, 57,  6, 28],
       [28, 44, 84, 30]], dtype=int32)

30. Stack two arrays vertically:
x = [1,2,3]
y = [4,5,6]

In [43]:
x = [1,2,3]
y = [4,5,6]
vstack=np.vstack([x,y])
vstack

array([[1, 2, 3],
       [4, 5, 6]])

31. Stack the same arrays horizontally.

In [44]:
hstack=np.hstack((x,y))
hstack

array([1, 2, 3, 4, 5, 6])

32. Split an array of 12 numbers into 3 equal parts.

In [41]:
array=np.random.randint(0,100,12)
array

array([26,  8, 78, 14, 89, 41, 76, 50, 62, 95, 51, 95], dtype=int32)

In [42]:
np.split(array,3)

[array([26,  8, 78, 14], dtype=int32),
 array([89, 41, 76, 50], dtype=int32),
 array([62, 95, 51, 95], dtype=int32)]

33. Concatenate three separate 1D arrays into one final array.

In [39]:
a1,a2,a3=np.arange(0,6),np.arange(6,11),np.arange(11,16)

In [40]:
a=np.concat((a1,a2,a3))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

34. Repeat each element of an array 3 times using NumPy.

In [36]:
a=np.arange(0,5,dtype=int)
a

array([0, 1, 2, 3, 4])

In [37]:
rep=a.repeat(3)
rep

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

getting random float numbers

In [34]:
b=np.random.uniform(low=1.0,high=10.0,size=10)
b

array([3.9266499 , 7.56645561, 6.73801724, 8.98491468, 5.24993433,
       2.07634821, 7.41920309, 7.84706544, 6.05149478, 7.93870462])

### 📌 SECTION E — Broadcasting, Vectorization & Random

35. Add a 1D array to a 2D array using broadcasting (3×3 + 1×3).

In [31]:
a1=np.random.randint(0,100,size=[3,3])
a1

array([[ 4, 40, 27],
       [ 6, 72, 71],
       [11, 33, 32]], dtype=int32)

In [32]:
a2=np.random.randint(1,100,[1,3])
a2

array([[48, 23, 62]], dtype=int32)

In [33]:
a=a1+a2
a

array([[ 52,  63,  89],
       [ 54,  95, 133],
       [ 59,  56,  94]], dtype=int32)

36. Multiply a column vector (3×1) with a row vector (1×4) → output must be 3×4.

In [29]:
row_vect=np.random.randint(1,100,[1,4])
col_vec=a2=np.random.randint(1,100,[3,1])
print(row_vect)
print(col_vec)

[[63 11 81  8]]
[[35]
 [35]
 [33]]


In [30]:
m=col_vec*row_vect
m

array([[2205,  385, 2835,  280],
       [2205,  385, 2835,  280],
       [2079,  363, 2673,  264]], dtype=int32)

37. Use broadcasting to subtract the column mean from each column of a 5×5 matrix.

In [24]:
array=np.random.randint(1,100,size=[5,5])
array

array([[72, 78, 87, 62, 40],
       [85, 80, 82, 53, 24],
       [26, 89, 60, 41, 29],
       [15, 45, 65, 89, 71],
       [ 9, 88,  1,  8, 88]], dtype=int32)

the columns and rows of the matrix can be split in rows and columns using vsplit and Hsplit

In [25]:
col=np.hsplit(array,5)
col

[array([[72],
        [85],
        [26],
        [15],
        [ 9]], dtype=int32),
 array([[78],
        [80],
        [89],
        [45],
        [88]], dtype=int32),
 array([[87],
        [82],
        [60],
        [65],
        [ 1]], dtype=int32),
 array([[62],
        [53],
        [41],
        [89],
        [ 8]], dtype=int32),
 array([[40],
        [24],
        [29],
        [71],
        [88]], dtype=int32)]

In [26]:
np.vsplit(array,5)

[array([[72, 78, 87, 62, 40]], dtype=int32),
 array([[85, 80, 82, 53, 24]], dtype=int32),
 array([[26, 89, 60, 41, 29]], dtype=int32),
 array([[15, 45, 65, 89, 71]], dtype=int32),
 array([[ 9, 88,  1,  8, 88]], dtype=int32)]

In [27]:
col[4]

array([[40],
       [24],
       [29],
       [71],
       [88]], dtype=int32)

in numpy azis=0 means column wise and axis 1 is row wise 

In [21]:
colmean=np.mean(array,axis=0)
r=array-colmean
r

array([ 2.,  0., -1., -2.,  1.])

38. Generate a 4×4 matrix of random floats (0–1) with seed=42.

In [10]:
np.random.seed(42)
array=np.random.rand(4,4)
array

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

39. Shuffle an array randomly using NumPy only (no Python shuffle).

In [18]:
array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array)

[5 3 2 1 4]


40. Real Analyst Scenario:
You have 24 months of monthly sales:
sales = np.arange(1,25)
Reshape it into 12 rows × 2 columns (12 months × 2 years) for comparison.

In [19]:
sales=np.random.randint(1000,20000,24)
sales

array([11233, 12016,  3612, 16787, 18159, 13206,  9226, 15541,  4152,
        2585,  4943,  2021, 12653, 11805, 14417,  8989, 10692, 13990,
        7873,  6675,  1161,  5297,  1995, 12534], dtype=int32)

In [20]:
year_sale=sales.reshape(12,2)
year_sale

array([[11233, 12016],
       [ 3612, 16787],
       [18159, 13206],
       [ 9226, 15541],
       [ 4152,  2585],
       [ 4943,  2021],
       [12653, 11805],
       [14417,  8989],
       [10692, 13990],
       [ 7873,  6675],
       [ 1161,  5297],
       [ 1995, 12534]], dtype=int32)

### END