### START

### NUMPY PYTHON LIBRARY
- the practice set for this library contains 40 questions

In [1]:
import numpy as np

1. Create a NumPy array from 1 to 100 (inclusive).

In [3]:
array1=np.arange(1,101)
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

2. Create a 5×5 matrix filled with random integers between 10 and 99. 

In [8]:
array=np.random.randint(10,99,[5,5])
array

array([[49, 76, 17, 75, 75],
       [43, 88, 94, 90, 64],
       [41, 51, 53, 82, 76],
       [15, 15, 36, 67, 54],
       [25, 21, 64, 80, 50]], dtype=int32)

3. Generate an array of 50 evenly spaced numbers between 0 and 5. 

In [11]:
array2=np.linspace(0,5,50)
array2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

4. Convert the list below into a NumPy float array: 
[10, 20, 30, 40, 50] 

In [18]:
lists=[10,20,30,40,50]
array3=np.array(lists,dtype=float)
array3

array([10., 20., 30., 40., 50.])

5. Create a 10-element array of zeroes and replace the 5th index with the 
value 99. 

In [29]:
array4=np.zeros(10,dtype=int)
array4[4]=99
array4

array([ 0,  0,  0,  0, 99,  0,  0,  0,  0,  0])

6. Create an array of shape (3,4) with random floats and round the values to 2 
decimals. 

In [ ]:
array5=np.random.randn(3,4)
array5

array([[ 0.14914612, -0.05053152, -1.00948836,  0.47021505],
       [-1.00336061, -1.45298376,  0.53924758,  0.07444522],
       [-0.22713625, -1.52341882,  0.9281897 ,  1.35668056]])

7. Create a 4×4 identity matrix.

In [38]:
array6=np.eye(4,4,dtype=int)
array6

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])